# Arduino Makefile, see https://github.com/sudar/Arduino-Makefile (it's awesome!)
BOARD_TAG    = atmega328
ARDUINO_PORT = /dev/ttyACM1
ARDUINO_LIBS =
AVR_TOOLS_DIR = /usr

CFLAGS_STD = -g
CXXFLAGS_STD = -g

include /usr/share/arduino/Arduino.mk

