## Arduino Makefile, see https://github.com/sudar/Arduino-Makefile (it's awesome!)
#ARDUINO_DIR = /home/schwager/bin/arduino-1.6.8
ARDUINO_DIR = /home/schwager/bin/arduino-1.8.5
#ARDMK_DIR = /home/schwager/Projects/Arduino/libraries/EnableInterrupt/examples/Simple
ARDMK_DIR = /usr/share/arduino
#AVR_TOOLS_DIR = /home/schwager/bin/arduino-1.6.8/hardware/tools/avr
AVR_TOOLS_DIR = /home/schwager/bin/arduino-1.8.5/hardware/tools/avr

BOARD_TAG    = pro
BOARD_SUB    = 16MHzatmega328
ARDUINO_PORT = /dev/ttyUSB0
##BOARD_TAG    = 2560
##ARDUINO_PORT = /dev/ttyACM0
#ARDUINO_LIBS =
#AVR_TOOLS_DIR = /usr
#
#CFLAGS_STD = -g
#CXXFLAGS_STD = -g
#
#include /usr/share/arduino/Arduino.mk

########################################################################
## Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile
#

#ARDUINO_DIR = /home/schwager/bin/arduino-1.6.4
#BOARD_SUB = atmega1284p
#CFLAGS_STD = -g -I /home/schwager/sketchbook/hardware/mighty-1284p-master/variants/standard
#CXXFLAGS_STD = -g -I /home/schwager/sketchbook/hardware/mighty-1284p-master/variants/standard
#  

#ISP_PROG = usbasp
# from boards.txt
#BOARD_TAG = mighty_opt
#ALTERNATE_CORE = mighty-1284p-master
# This is set in the boards.txt file.
#F_CPU = 16000000L

include /usr/share/arduino/Arduino.mk
