# Arduino Makefile, see https://github.com/sudar/Arduino-Makefile (it's awesome!)
BOARD_TAG    = 2560
ARDUINO_PORT = /dev/ttyACM0
ARDUINO_LIBS =

CFLAGS_STD = -g
CXXFLAGS_STD = -g

include /usr/share/arduino/Arduino.mk

